### ISSUE TITLE
AssertionError: could not extract Python type from node

### ISSUE THREAD

**Issue by cancan101** [sqlalchemy/sqlalchemy2-stubs#11]
**Describe the bug**
Running `mypy . --show-traceback` I am getting this stacktrace:
```
version: 0.812
Traceback (most recent call last):
  File "mypy/semanal.py", line 4835, in accept
  File "mypy/nodes.py", line 950, in accept
  File "mypy/semanal.py", line 1048, in visit_class_def
  File "mypy/semanal.py", line 1125, in analyze_class
  File "mypy/semanal.py", line 1134, in analyze_class_body_common
  File "mypy/semanal.py", line 1194, in apply_class_plugin_hooks
  File "/Users/alex/.pyenv/versions/3.8.2/envs/my-app/lib/python3.8/site-packages/sqlalchemy/ext/mypy/plugin.py", line 159, in _base_cls_hook
    decl_class._scan_declarative_assignments_and_apply_types(ctx.cls, ctx.api)
  File "/Users/alex/.pyenv/versions/3.8.2/envs/my-app/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 123, in _scan_declarative_assignments_and_apply_types
    _scan_declarative_assignment_stmt(cls, api, stmt, cls_metadata)
  File "/Users/alex/.pyenv/versions/3.8.2/envs/my-app/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 380, in _scan_declarative_assignment_stmt
    python_type_for_type = _infer_type_from_decl_column(
  File "/Users/alex/.pyenv/versions/3.8.2/envs/my-app/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 714, in _infer_type_from_decl_column
    python_type_for_type = _extract_python_type_from_typeengine(
  File "/Users/alex/.pyenv/versions/3.8.2/envs/my-app/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 989, in _extract_python_type_from_typeengine
    assert False, "could not extract Python type from node: %s" % node
AssertionError: could not extract Python type from node: TypeInfo(
  Name(sqlalchemy.sql.sqltypes.Boolean)
  Bases(sqlalchemy.sql.type_api.Emulated, sqlalchemy.sql.type_api.TypeEngine[builtins.bool], sqlalchemy.sql.sqltypes.SchemaType)
  Mro(sqlalchemy.sql.sqltypes.Boolean, sqlalchemy.sql.type_api.Emulated, sqlalchemy.sql.type_api.TypeEngine, sqlalchemy.sql.visitors.Traversible, sqlalchemy.sql.sqltypes.SchemaType, sqlalchemy.sql.base.SchemaEventTarget, builtins.object)
  Names(
    __init__
    __visit_name__ (builtins.str)
    bind_processor
    create_constraint (Any)
    literal_processor
    name (Any)
    native (builtins.bool)
    python_type
    result_processor))
```

**Expected behavior**
mypy runs without dying.

**To Reproduce**
I haven't yet figured out a stripped down example. Working on it

**Versions.**
```
sqlalchemy2-stubs==0.0.1a4
sqlalchemy[postgresql]==1.4.2
```

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
this is https://github.com/sqlalchemy/sqlalchemy/issues/6109 already fixed.
