### ISSUE TITLE
Mypy complains extension is not a directory

### ISSUE THREAD

**Issue by kracekumar** [sqlalchemy/sqlalchemy2-stubs#118]
**Describe the bug**

mypy config

```bash
$cat mypy.ini
[mypy]
plugins = sqlalchemy.ext.mypy.plugin
```

I'm trying  annotate flask-sqlalchemy library in `out` directory and when I run mypy like 
`MYPYPATH="out" prun mypy example.py`. Here `prun` is alias to `poetry run`. the command produces following output
example.py contains no flask sqlalchemy imports

```
Error constructing plugin instance of SQLAlchemyPlugin

Traceback (most recent call last):
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/flask-sqlalchemy-KzL4aHKU-py3.9/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/flask-sqlalchemy-KzL4aHKU-py3.9/lib/python3.9/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 90, in main
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 228, in _build
  File "mypy/build.py", line 472, in load_plugins
  File "mypy/build.py", line 451, in load_plugins_from_config
  File "mypy/build.py", line 491, in take_module_snapshot
NotADirectoryError: [Errno 20] Not a directory: '/Users/user/Library/Caches/pypoetry/virtualenvs/flask-sqlalchemy-KzL4aHKU-py3.9/lib/python3.9/site-packages/SQLAlchemy-1.4.18-py3.9-macosx-11-x86_64.egg/sqlalchemy/ext/mypy/plugin.py'

```
**Expected behavior**

The mypy shouldn't complain sqlalchemy plugin is invalid.

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22).

**Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**.  The test case must illustrate the problem **without** using any third party SQLAlchemy extensions.  Otherwise, please report the bug to those projects first.

```py
# Insert code here
from sqlalchemy import orm
```

**Error**

```
poetry run mypy example.py

Python 2.7 will no longer be supported in the next feature release of Poetry (1.2).
You should consider updating your Python version to a supported one.

Note that you will still be able to manage Python 2.7 projects by using the env command.
See https://python-poetry.org/docs/managing-environments/ for more information.

Error constructing plugin instance of SQLAlchemyPlugin

Traceback (most recent call last):
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/flask-sqlalchemy-KzL4aHKU-py3.9/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/flask-sqlalchemy-KzL4aHKU-py3.9/lib/python3.9/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 90, in main
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 228, in _build
  File "mypy/build.py", line 472, in load_plugins
  File "mypy/build.py", line 451, in load_plugins_from_config
  File "mypy/build.py", line 491, in take_module_snapshot
NotADirectoryError: [Errno 20] Not a directory: '/Users/user/Library/Caches/pypoetry/virtualenvs/flask-sqlalchemy-KzL4aHKU-py3.9/lib/python3.9/site-packages/SQLAlchemy-1.4.18-py3.9-macosx-11-x86_64.egg/sqlalchemy/ext/mypy/plugin.py'
```

```
# Copy error here. Please include the full stack trace.
```

**Versions.**
 - OS: Mac OSX
 - Python: 3.9.4
 - SQLAlchemy: 1.4.18
 - mypy: 0.812/0.902
 - SQLAlchemy2-stubs: 0.0.2a2

**Additional context**

I tried a different versions of mypy like `0.812` and `0.902`.  The error remains same. Not sure where I should report here or in mypy repository, starting here.

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

I think the issue may be of poetry. Can you try installing sqlalchemy using pip?

I'm not sure if we need to do something specific to tell poetry not to install sqlalchemy as a zip

**Comment by kracekumar** [comment]
Thanks, it helped to resolve `Error constructing plugin instance of SQLAlchemyPlugin`. Now, it works as expected.

**Comment by kracekumar** [comment]
I'll try to report in poetry. closing this.

**Comment by CaselIT** [comment]
Thanks, please report back if we can change something on our end to make this work
