### ISSUE TITLE
implement support to intercept as_declarative()

### ISSUE THREAD

**Issue by ninjaaron** [sqlalchemy/sqlalchemy2-stubs#2]
I installed the the type stubs and configured the mypy plugin as directed in the [documentation](https://docs.sqlalchemy.org/en/14/orm/extensions/mypy.html)

My database is defined like this:

```python
@as_declarative()
class Base:
    def __repr__(self):
        name = self.__class__.__name__
        attrs = (
            "%s=%r" % (attr, getattr(self, attr))
            for attr in self._sa_class_manager.keys()
            if not (attr[-2:] == "id" or isinstance(getattr(self, attr), list))
        )
        return name + "(%s)" % ", ".join(attrs)


class Source(Base):
    __tablename__ = "sources"
    id = sa.Column(sa.Integer, primary_key=True)
    address = sa.Column(sa.String, index=True)
    match_id = sa.Column(sa.Integer, sa.ForeignKey("matches.id"))

    match = relationship("Match", back_populates="sources")


class Match(Base):
    __tablename__ = "matches"
    id = sa.Column(sa.Integer, primary_key=True)
    original_id = sa.Column(sa.Integer, sa.ForeignKey("original.id"))
    romanized_id = sa.Column(sa.Integer, sa.ForeignKey("romanized.id"))
    count = sa.Column(sa.Integer)

    original = relationship("Original", back_populates="matches")
    romanized = relationship("Romanized", back_populates="matches")
    sources = relationship("Source", back_populates="match")


sa.Index("matches_idx", Match.original_id, Match.romanized_id, unique=True)


class Standard(Base):
    __tablename__ = "standards"
    id = sa.Column(sa.Integer, primary_key=True)
    st = sa.Column(sa.String, index=True, unique=True)


class Original(Base):
    __tablename__ = "original"
    id = sa.Column(sa.Integer, primary_key=True)
    form = sa.Column(sa.String, index=True, unique=True)

    matches = relationship("Match", back_populates="original")


class Romanized(Base):
    __tablename__ = "romanized"
    id = sa.Column(sa.Integer, primary_key=True)
    form = sa.Column(sa.String, index=True)
    standard_id = sa.Column(sa.Integer, sa.ForeignKey("standards.id"))

    standard = relationship(Standard)
    matches = relationship("Match", back_populates="romanized")


sa.Index("standard_form", Romanized.form, Romanized.standard_id, unique=True)
```

When I run mypy, I get these errors:

```bash
$ mypy deromanize 
deromanize/cacheutils.py:201: error: Need type annotation for 'match'
deromanize/cacheutils.py:211: error: Need type annotation for 'original'
deromanize/cacheutils.py:212: error: Need type annotation for 'romanized'
deromanize/cacheutils.py:213: error: Need type annotation for 'sources'
deromanize/cacheutils.py:230: error: Need type annotation for 'matches'
deromanize/cacheutils.py:239: error: Need type annotation for 'standard'
deromanize/cacheutils.py:240: error: Need type annotation for 'matches'
Found 7 errors in 1 file (checked 6 source files)
```

This does not match the documented error message:

```
test3.py:22: error: [SQLAlchemy Mypy plugin] Can't infer scalar or
collection for ORM mapped expression assigned to attribute 'user'
if both 'uselist' and 'collection_class' arguments are absent from the
relationship(); please specify a type annotation on the left hand side.
Found 1 error in 1 file (checked 1 source file)
```

Furthermore, when I attempt to add annotations, that doesn't work either:

```python
class Source(Base):
    __tablename__ = "sources"
    id = sa.Column(sa.Integer, primary_key=True)
    address = sa.Column(sa.String, index=True)
    match_id = sa.Column(sa.Integer, sa.ForeignKey("matches.id"))

    match: 'Match' = relationship("Match", back_populates="sources")
```

```bash
deromanize/cacheutils.py:201: error: Incompatible types in assignment (expression has type "RelationshipProperty[<nothing>]", variable has type "Match")
```

Am I doing something wrong or is this a bug?

**Comment by zzzeek** [comment]
this is a bug!  I did not implement the plugin's support for as_declarative() yet :)      as a temporary workaround, if you declare your base using this pattern: https://docs.sqlalchemy.org/en/14/orm/mapping_styles.html#creating-an-explicit-base-non-dynamically-for-use-with-mypy-similar   it should work better.

thanks for testing!  mypy plugin is totally new and not tested with anyone other than my own made up test cases.

**Comment by ninjaaron** [comment]
Thanks! I implemented my Base class as the link suggested, and I got this error when running MyPy:

```python
deromanize/cacheutils.py:204: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.820+dev.ac66403cb4374b858786350b96e7f5972db84bcd
Traceback (most recent call last):
  File "/home/ninjaaron/src/fid-judaica/packages/venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/main.py", line 98, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/build.py", line 179, in build
    result = _build(
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/build.py", line 253, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/build.py", line 2688, in dispatch
    process_graph(graph, manager)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/build.py", line 3012, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/build.py", line 3104, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/semanal_main.py", line 78, in semantic_analysis_for_scc
    process_top_levels(graph, scc, patches)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/semanal_main.py", line 199, in process_top_levels
    deferred, incomplete, progress = semantic_analyze_target(next_id, state,
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/semanal_main.py", line 326, in semantic_analyze_target
    analyzer.refresh_partial(refresh_node,
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/semanal.py", line 394, in refresh_partial
    self.refresh_top_level(node)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/semanal.py", line 405, in refresh_top_level
    self.accept(d)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/semanal.py", line 4835, in accept
    node.accept(self)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/nodes.py", line 950, in accept
    return visitor.visit_class_def(self)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/semanal.py", line 1048, in visit_class_def
    self.analyze_class(defn)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/semanal.py", line 1125, in analyze_class
    self.analyze_class_body_common(defn)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/semanal.py", line 1134, in analyze_class_body_common
    self.apply_class_plugin_hooks(defn)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/mypy/semanal.py", line 1194, in apply_class_plugin_hooks
    hook(ClassDefContext(defn, base_expr, self))
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/plugin.py", line 159, in _base_cls_hook
    decl_class._scan_declarative_assignments_and_apply_types(ctx.cls, ctx.api)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 123, in _scan_declarative_assignments_and_apply_types
    _scan_declarative_assignment_stmt(cls, api, stmt, cls_metadata)
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 380, in _scan_declarative_assignment_stmt
    python_type_for_type = _infer_type_from_decl_column(
  File "/home/ninjaaron/src/fid-judaica/packages/venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 708, in _infer_type_from_decl_column
    assert False
AssertionError: 
deromanize/cacheutils.py:204: : note: use --pdb to drop into pdb
```

**Comment by zzzeek** [comment]
OK, this mypy thing is going to take a long time to get right.   what's throwing it off is the "sa." module prefix, which apparently I have to handle differently:

```

(Pdb) column_arg
<mypy.nodes.MemberExpr object at 0x7f4dd14c3af0>
(Pdb) print(column_arg)
MemberExpr:28(
  NameExpr(sa [sqlalchemy])
  Integer [sqlalchemy.sql.sqltypes.Integer])
```


this patch fixes it:

```
diff --git a/lib/sqlalchemy/ext/mypy/decl_class.py b/lib/sqlalchemy/ext/mypy/decl_class.py
index f5215ca1c..7a0c251c3 100644
--- a/lib/sqlalchemy/ext/mypy/decl_class.py
+++ b/lib/sqlalchemy/ext/mypy/decl_class.py
@@ -693,7 +693,7 @@ def _infer_type_from_decl_column(
             # x = Column(String(50))
             callee = column_arg.callee
             break
-        elif isinstance(column_arg, nodes.NameExpr):
+        elif isinstance(column_arg, (nodes.NameExpr, nodes.MemberExpr)):
             if isinstance(column_arg.node, TypeInfo):
                 # x = Column(String)
                 callee = column_arg

```

I can get your test script to then come out green like this:

```python
import sqlalchemy as sa
from typing import List
from sqlalchemy.orm import relationship
from sqlalchemy.orm import registry, subqueryload
from sqlalchemy.orm.decl_api import DeclarativeMeta

mapper_registry = registry()

class Base(metaclass=DeclarativeMeta):
    __abstract__ = True

    # these are supplied by the sqlalchemy2-stubs, so may be omitted
    # when they are installed
    registry = mapper_registry
    metadata = mapper_registry.metadata

    def __repr__(self):
        name = self.__class__.__name__
        attrs = (
            "%s=%r" % (attr, getattr(self, attr))
            for attr in self._sa_class_manager.keys()
            if not (attr[-2:] == "id" or isinstance(getattr(self, attr), list))
        )
        return name + "(%s)" % ", ".join(attrs)


class Source(Base):
    __tablename__ = "sources"
    id = sa.Column(sa.Integer, primary_key=True)
    address = sa.Column(sa.String, index=True)
    match_id = sa.Column(sa.Integer, sa.ForeignKey("matches.id"))

    match: "Match" = relationship("Match", back_populates="sources")


class Match(Base):
    __tablename__ = "matches"
    id = sa.Column(sa.Integer, primary_key=True)
    original_id = sa.Column(sa.Integer, sa.ForeignKey("original.id"))
    romanized_id = sa.Column(sa.Integer, sa.ForeignKey("romanized.id"))
    count = sa.Column(sa.Integer)

    original: "Original" = relationship("Original", back_populates="matches")
    romanized: "Romanized" = relationship("Romanized", back_populates="matches")
    sources: "Source" = relationship("Source", back_populates="match")


sa.Index("matches_idx", Match.original_id, Match.romanized_id, unique=True)


class Standard(Base):
    __tablename__ = "standards"
    id = sa.Column(sa.Integer, primary_key=True)
    st = sa.Column(sa.String, index=True, unique=True)


class Original(Base):
    __tablename__ = "original"
    id = sa.Column(sa.Integer, primary_key=True)
    form = sa.Column(sa.String, index=True, unique=True)

    matches: List["Match"] = relationship("Match", back_populates="original")


class Romanized(Base):
    __tablename__ = "romanized"
    id = sa.Column(sa.Integer, primary_key=True)
    form = sa.Column(sa.String, index=True)
    standard_id = sa.Column(sa.Integer, sa.ForeignKey("standards.id"))

    standard : Standard = relationship(Standard)
    matches : Match = relationship("Match", back_populates="romanized")


sa.Index("standard_form", Romanized.form, Romanized.standard_id, unique=True)
```

so that's not too bad!  ill get that committed.

**Comment by zzzeek** [comment]
that's merged in d0812a1abf903f6b5f1a0bfb19f8c87a665f8309.  this issue is for the as_declarative() thing, didn't do that part yet.

**Comment by ninjaaron** [comment]
Thanks! It typechecks on my side, too, with this patch!

**Comment by zzzeek** [comment]
I've got as_declarative implemented at https://github.com/sqlalchemy/sqlalchemy/commit/acd0122c2cb9ad0fe0cf92b306ea50dd51ec88b8 .
