### ISSUE TITLE
Issue Following: Creating an Explicit Base Non-Dynamically

### ISSUE THREAD

**Issue by cancan101** [sqlalchemy/sqlalchemy2-stubs#57]
On SQLA 1.3 + the Dropbox stubs, I use `Base = declarative_base(metadata=meta)` for my models' base class and everything works fine. When  I upgrade to 1.4 + the new stubs, using that `Base` for my models generates the following mypy warning:
```
api/models.py:1121: error: Variable "api.database.Base" is not valid as a type
api/models.py:1121: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
```

So first I tried:
```
from sqlalchemy.orm import registry
....
mapper_registry = registry(metadata=meta)
Base = mapper_registry.generate_base()
```
however I get the same warning. I do get an additional warning:
```
error: Module 'sqlalchemy.orm' has no attribute 'registry'
```

 [I then tried](https://docs.sqlalchemy.org/en/14/orm/mapping_styles.html#creating-an-explicit-base-non-dynamically-for-use-with-mypy-similar):
```
mapper_registry = registry(metadata=meta)

class Base(metaclass=DeclarativeMeta):
    __abstract__ = True

    registry = mapper_registry
    metadata = mapper_registry.metadata
```
however I then get:
```
 mypy . --show-traceback
api/database.py:16: error: Module 'sqlalchemy.orm' has no attribute 'registry'
./api/models.py:34: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.812
Traceback (most recent call last):
  File "mypy/semanal.py", line 4835, in accept
  File "mypy/nodes.py", line 950, in accept
  File "mypy/semanal.py", line 1048, in visit_class_def
  File "mypy/semanal.py", line 1125, in analyze_class
  File "mypy/semanal.py", line 1134, in analyze_class_body_common
  File "mypy/semanal.py", line 1194, in apply_class_plugin_hooks
  File "/Users/alex/.pyenv/versions/3.8.2/envs/api/lib/python3.8/site-packages/sqlalchemy/ext/mypy/plugin.py", line 193, in _base_cls_hook
    _add_globals(ctx)
  File "/Users/alex/.pyenv/versions/3.8.2/envs/api/lib/python3.8/site-packages/sqlalchemy/ext/mypy/plugin.py", line 184, in _add_globals
    util.add_global(ctx, "sqlalchemy.orm.attributes", "Mapped", "__sa_Mapped")
  File "/Users/alex/.pyenv/versions/3.8.2/envs/api/lib/python3.8/site-packages/sqlalchemy/ext/mypy/util.py", line 79, in add_global
    lookup_sym: SymbolTableNode = ctx.api.modules[module].names[
KeyError: 'Mapped'
./api/models.py:34: : note: use --pdb to drop into pdb
```

**Comment by zzzeek** [comment]
please provide specifics

no warnings here:
```python


from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy.orm import declarative_base

Base = declarative_base(metadata=MetaData())


class U(Base):
    __tablename__ = "x"
    id = Column(Integer, primary_key=True)
```


```
$ mypy test3.py 
Success: no issues found in 1 source file

```
